<?php
/**
 * http://pluginscorner.com
 *
 * @package instant-post-types
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}

?>
<div class="cpt-pc-button-container animated bounceInUp">
	<a href="javascript:void(0)" class="cpt-pc-show-options cpt-pc-btn cpt-pc-btn-block"><i class="cpt-pc-material-icons cpt-pc-right cpt-pc-close cpt-pc-tooltipped" data-position="top" data-tooltip="Manage Post Types and Taxonomies">add</i></a>
</div>
