<?php
/**
 * http://pluginscorner.com
 *
 * @package instant-post-types
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}

?>

<div class="cpt-pc-card cpt-pc-options-container">
	<i class="cpt-pc-material-icons cpt-pc-right cpt-pc-close">clear</i>
	<h5 class="cpt-pc-title cpt-pc-title-post-types"><?php echo __( 'Post Types', CPT_PC_Const::T ) ?> <a href="javascript:void(0)" class="cpt-pc-btn cpt-pc-btn-small cpt-pc-add-cpt"><?php echo __( 'Add', CPT_PC_Const::T ) ?></a></h5>

    <# if (CPT_PC.globals.post_types.length > 0) { #>
        <div class="cpt-pc-row">
            <div class="cpt-pc-col cpt-pc-s2 cpt-pc-no-padding">
                <strong><?php echo __( 'Name', CPT_PC_Const::T ) ?></strong>
            </div>
            <div class="cpt-pc-col cpt-pc-s2 cpt-pc-no-padding">
                <strong><?php echo __( 'Slug', CPT_PC_Const::T ) ?></strong>
            </div>
            <div class="cpt-pc-col cpt-pc-s6 cpt-pc-no-padding">
                <strong><?php echo __( 'Description', CPT_PC_Const::T ) ?></strong>
            </div>
            <div class="cpt-pc-col cpt-pc-s2 cpt-pc-no-padding">
                <strong class="cpt-pc-right"><?php echo __( 'Actions', CPT_PC_Const::T ) ?></strong>
            </div>
        </div>
    <# } #>
	<div class="cpt-pc-post-types"></div>
	<h5 class="cpt-pc-title"><?php echo __( 'Taxonomies', CPT_PC_Const::T ) ?> <a href="javascript:void(0)" class="cpt-pc-btn cpt-pc-btn-small cpt-pc-add-tax"><?php echo __( 'Add', CPT_PC_Const::T ) ?></a></h5>
    <# if (CPT_PC.globals.taxonomies.length > 0) { #>
        <div class="cpt-pc-row">
            <div class="cpt-pc-col cpt-pc-s2 cpt-pc-no-padding">
                <strong><?php echo __( 'Name', CPT_PC_Const::T ) ?></strong>
            </div>
            <div class="cpt-pc-col cpt-pc-s2 cpt-pc-no-padding">
                <strong><?php echo __( 'Slug', CPT_PC_Const::T ) ?></strong>
            </div>
            <div class="cpt-pc-col cpt-pc-s2 cpt-pc-no-padding">
                <strong><?php echo __( 'Post Types', CPT_PC_Const::T ) ?></strong>
            </div>
            <div class="cpt-pc-col cpt-pc-s4 cpt-pc-no-padding">
                <strong><?php echo __( 'Description', CPT_PC_Const::T ) ?></strong>
            </div>
            <div class="cpt-pc-col cpt-pc-s2 cpt-pc-no-padding">
                <strong class="cpt-pc-right"><?php echo __( 'Actions', CPT_PC_Const::T ) ?></strong>
            </div>
        </div>
    <# } #>
	<div class="cpt-pc-row cpt-pc-no-margin cpt-pc-taxonomies"></div>
</div>
