<?php
/**
 * http://pluginscorner.com
 *
 * @package instant-post-types
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}
?>

<div class="cpt-pc-preloader-overlay cpt-pc-page-preloader" id="cpt-pc-hide-onload" style="display: none">
	<div class="cpt-pc-card-preloader">
		<div class="cpt-pc-preloader-wrapper cpt-pc-bigger cpt-pc-active">
			<div class="cpt-pc-spinner-layer cpt-pc-spinner-green-only">
				<div class="cpt-pc-circle-clipper cpt-pc-left">
					<div class="cpt-pc-circle"></div>
				</div><div class="cpt-pc-gap-patch">
					<div class="cpt-pc-circle"></div>
				</div><div class="cpt-pc-circle-clipper cpt-pc-right">
					<div class="cpt-pc-circle"></div>
				</div>
			</div>
		</div>
	</div>
</div>
