<?php
/**
 * http://pluginscorner.com
 *
 * @package instant-post-types
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}

?>
<h5><?php echo __( 'Advanced Settings', CPT_PC_Const::T ) ?></h5>
<div class="cpt-pc-row">
	<div class="cpt-pc-col cpt-pc-s4 cpt-pc-input-field">
		<input placeholder="Query Var" name="query_var" value="<#= model.get('query_var') #>" id="ect-tax-query-var" class="cpt-pc-input-change" type="text">
		<label for="ect-tax-query-var"><?php echo __( 'Query Var', CPT_PC_Const::T ) ?></label>
		<i class="cpt-pc-material-icons cpt-pc-info-icon cpt-pc-tooltipped" data-position="top"
		   data-tooltip="Sets the query_var key for this taxonomy.">info_outline</i>
	</div>
	<div class="cpt-pc-col cpt-pc-s4 cpt-pc-input-field">
		<input placeholder="Meta box callback function" name="meta_box_cb" value="<#= model.get('meta_box_cb') #>" id="ect-tax-meta-box-cb" class="cpt-pc-input-change"
			   type="text">
		<label for="ect-tax-meta-box-cb"><?php echo __( 'Meta box callback', CPT_PC_Const::T ) ?></label>
		<i class="cpt-pc-material-icons cpt-pc-info-icon cpt-pc-tooltipped" data-position="top"
		   data-tooltip="Please leave this empty if you don't know what this does.">info_outline</i>
	</div>
	<div class="cpt-pc-col cpt-pc-s4 cpt-pc-input-field">
		<input placeholder="Update Count Callback Function" name="update_count_callback" value="<#= model.get('update_count_callback') #>" id="ect-tax-update-count-callback" class="cpt-pc-input-change"
			   type="text">
		<label for="ect-tax-update-count-callback"><?php echo __( 'Update Count Callback', CPT_PC_Const::T ) ?></label>
		<i class="cpt-pc-material-icons cpt-pc-info-icon cpt-pc-tooltipped" data-position="top"
		   data-tooltip="A function name that will be called when the count of an associated $object_type, such as post, is updated. Works much like a hook.">info_outline</i>
	</div>
	<div class="cpt-pc-col cpt-pc-s4 cpt-pc-input-field">
		<input placeholder="Rewrite the slug" name="rewrite" value="<#= model.get('rewrite').slug #>" id="ect-tax-rewrite-slug" class="cpt-pc-input-change" type="text">
		<label for="ect-tax-rewrite-slug"><?php echo __( 'Rewrite the slug', CPT_PC_Const::T ) ?></label>
		<i class="cpt-pc-material-icons cpt-pc-info-icon cpt-pc-tooltipped" data-position="top"
		   data-tooltip="Customize the permalink structure slug. Should be translatable.">info_outline</i>
	</div>
</div>
<div class="cpt-pc-row">
	<div class="cpt-pc-col cpt-pc-s3">
		<label for="ect-tax-show-tagcloud"><?php echo __( 'Show in Tag Cloud Widget ?', CPT_PC_Const::T ) ?></label>
		<div class="cpt-pc-switch">
			<label>
				<?php echo __( 'No', CPT_PC_Const::T ) ?>
				<input id="ect-tax-show-tagcloud" name="show_tagcloud"
				<#= model.get('show_tagcloud') ? 'checked="checked"' : '' #> type="checkbox">
					<span class="cpt-pc-lever"></span>
					<?php echo __( 'Yes', CPT_PC_Const::T ) ?>
			</label>
		</div>
	</div>
	<div class="cpt-pc-col cpt-pc-s3">
		<label for="ect-tax-show-in-quick-edit"><?php echo __( 'Show in Quick Edit ?', CPT_PC_Const::T ) ?></label>
		<div class="cpt-pc-switch">
			<label>
				<?php echo __( 'No', CPT_PC_Const::T ) ?>
				<input id="ect-tax-show-in-quick-edit" name="show_in_quick_edit"
				<#= model.get('show_in_quick_edit') ? 'checked="checked"' : '' #> type="checkbox">
					<span class="cpt-pc-lever"></span>
					<?php echo __( 'Yes', CPT_PC_Const::T ) ?>
			</label>
		</div>
	</div>
	<div class="cpt-pc-col cpt-pc-s3">
		<label for="ect-tax-show-admin-column"><?php echo __( 'Show Admin Column?', CPT_PC_Const::T ) ?></label>
		<div class="cpt-pc-switch">
			<label>
				<?php echo __( 'No', CPT_PC_Const::T ) ?>
				<input id="ect-tax-show-admin-column" name="show_admin_column"
				<#= model.get('show_admin_column') ? 'checked="checked"' : '' #> type="checkbox">
					<span class="cpt-pc-lever"></span>
					<?php echo __( 'Yes', CPT_PC_Const::T ) ?>
			</label>
		</div>
	</div>
	<div class="cpt-pc-col cpt-pc-s3">
		<label for="ect-tax-show-nav"><?php echo __( 'Show in nav menus ?', CPT_PC_Const::T ) ?></label>
		<div class="cpt-pc-switch">
			<label>
				<?php echo __( 'No', CPT_PC_Const::T ) ?>
				<input id="ect-tax-show-nav" name="show_in_nav_menus"
				<#= model.get('show_in_nav_menus') ? 'checked="checked"' : '' #> type="checkbox">
					<span class="cpt-pc-lever"></span>
					<?php echo __( 'Yes', CPT_PC_Const::T ) ?>
			</label>
		</div>
	</div>
	<div class="cpt-pc-col cpt-pc-s3">
		<label for="ect-tax-sort"><?php echo __( 'Sort ?', CPT_PC_Const::T ) ?></label>
		<div class="cpt-pc-switch">
			<label>
				<?php echo __( 'No', CPT_PC_Const::T ) ?>
				<input id="ect-tax-sort" name="delete_with_user"
				<#= model.get('sort') ? 'checked="checked"' : '' #> type="checkbox">
					<span class="cpt-pc-lever"></span>
					<?php echo __( 'Yes', CPT_PC_Const::T ) ?>
			</label>
		</div>
	</div>
</div>
