<?php
/**
 * http://pluginscorner.com
 *
 * @package instant-post-types
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}

?>

<h5><?php echo __( 'General Settings', CPT_PC_Const::T ) ?></h5>
<div class="cpt-pc-row cpt-pc-no-margin">
	<div class="cpt-pc-col cpt-pc-s6 cpt-pc-input-field">
		<input placeholder="Taxonomy Name" name="singular_name" value="<#= model.get('labels').singular_name #>" id="cpt-pc-tax-name" type="text">
		<label for="cpt-pc-tax-name"><?php echo __( 'Name', CPT_PC_Const::T ) ?></label>
	</div>
	<div class="cpt-pc-col cpt-pc-s6 cpt-pc-input-field">
		<input placeholder="Taxonomy Slug" name="slug" value="<#= model.get('slug') #>" id="cpt-pc-tax-slug" data-field="slug" class="cpt-pc-input-change" type="text">
		<label for="cpt-pc-tax-slug"><?php echo __( 'Handle', CPT_PC_Const::T ) ?></label>
		<i class="cpt-pc-material-icons cpt-pc-info-icon cpt-pc-tooltipped" data-position="top"
		   data-tooltip="The name of the taxonomy. Name should only contain lowercase letters and the underscore character, and not be more than 32 characters long (database structure restriction).">info_outline</i>
	</div>
</div>
<div class="cpt-pc-row cpt-pc-no-margin">
	<div class="cpt-pc-col cpt-pc-s12 cpt-pc-input-field">
		<textarea id="cpt-pc-description" name="description" class="cpt-pc-materialize-textarea cpt-pc-input-change"><#= model.get('description') #></textarea>
		<label for="cpt-pc-description"><?php echo __( 'Description', CPT_PC_Const::T ) ?></label>
	</div>
</div>
<div class="cpt-pc-row cpt-pc-no-margin">
	<div class="cpt-pc-col cpt-pc-s3">
		<label for="cpt-pc-tax-public"><?php echo __( 'Public ?', CPT_PC_Const::T ) ?></label>
		<div class="cpt-pc-switch">
			<label>
				<?php echo __( 'No', CPT_PC_Const::T ) ?>
				<input id="cpt-pc-tax-public" name="public" <#= model.get('public') ? 'checked="checked"' : '' #> type="checkbox">
				<span class="cpt-pc-lever"></span>
				<?php echo __( 'Yes', CPT_PC_Const::T ) ?>
			</label>
		</div>
	</div>
	<div class="cpt-pc-col cpt-pc-s3">
		<label for="ect-cpt-ui"><?php echo __( 'Show in the UI ?', CPT_PC_Const::T ) ?></label>
		<div class="cpt-pc-switch">
			<label>
				<?php echo __( 'No', CPT_PC_Const::T ) ?>
				<input id="ect-cpt-ui" name="show_ui" <#= model.get('show_ui') ? 'checked="checked"' : '' #> type="checkbox">
				<span class="cpt-pc-lever"></span>
				<?php echo __( 'Yes', CPT_PC_Const::T ) ?>
			</label>
		</div>
	</div>
	<div class="cpt-pc-col cpt-pc-s3">
		<label for="ect-cpt-menu"><?php echo __( 'Show in the Menu ?', CPT_PC_Const::T ) ?></label>
		<div class="cpt-pc-switch">
			<label>
				<?php echo __( 'No', CPT_PC_Const::T ) ?>
				<input id="ect-cpt-menu" name="show_in_menu" <#= model.get('show_in_menu') ? 'checked="checked"' : '' #> type="checkbox">
				<span class="cpt-pc-lever"></span>
				<?php echo __( 'Yes', CPT_PC_Const::T ) ?>
			</label>
		</div>
	</div>
	<div class="cpt-pc-col cpt-pc-s3">
		<label for="ect-cpt-hierarchical"><?php echo __( 'Is this taxonomy hierarchical ?', CPT_PC_Const::T ) ?></label>
		<div class="cpt-pc-switch">
			<label>
				<?php echo __( 'No', CPT_PC_Const::T ) ?>
				<input id="ect-cpt-hierarchical" name="hierarchical" <#= model.get('hierarchical') ? 'checked="checked"' : '' #> type="checkbox">
				<span class="cpt-pc-lever"></span>
				<?php echo __( 'Yes', CPT_PC_Const::T ) ?>
			</label>
		</div>
	</div>
	<div class="cpt-pc-col cpt-pc-s12">
		<label for="ect-cpt-ui"><?php echo __( 'Attach Post Type', CPT_PC_Const::T ) ?></label>
		<div class="cpt-pc-post-types cpt-pc-row"></div>
	</div>
</div>
