<?php
/**
 * http://pluginscorner.com
 *
 * @package instant-post-types
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}

?>

<div class="cpt-pc-material-container">
	<h3 class="cpt-pc-modal-title cpt-pc-no-margin"><?php echo __( 'Getting Started Guide', CPT_PC_Const::T ) ?></h3>
	<div class="cpt-pc-modal-content">
		<h5 class="cpt-pc-teal-text"><?php _e( 'Thank You for installing Instant Post Types!' ) ?></h5>
		<br/>
		<h6><?php _e( 'Because this plugin allows you to create Custom Post Types and Custom Taxonomies on any screen, we prepared a small onscreen guide to help you  create your first Custom Post Type and Custom Taxonomy.' ) ?></h6>
		<br/>
		<h6 class="cpt-pc-teal-text"><strong><?php _e( 'Would you like to start the guide ?' ) ?></strong></h6>
		<br/>
	</div>

	<div class="cpt-pc-modal-footer">
		<div class="cpt-pc-row">
			<div class="cpt-pc-col cpt-pc-s6">
				<a href="javascript:void(0)" class="cpt-pc-btn cpt-pc-red cpt-pc-waves-light cpt-pc-left cpt-pc-no">
					<?php echo __( 'No i don\'t', CPT_PC_Const::T ) ?>
				</a>
			</div>
			<div class="cpt-pc-col cpt-pc-s6">
				<a href="javascript:void(0)" class="cpt-pc-btn cpt-pc-teal cpt-pc-waves-light cpt-pc-right cpt-pc-yes">
					<?php echo __( 'Yes i do', CPT_PC_Const::T ) ?>
				</a>
			</div>
		</div>
	</div>
</div>

