<?php
/**
 * http://pluginscorner.com
 *
 * @package instant-post-types
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // Silence is golden
}

?>
<div class="cpt-pc-row cpt-pc-no-margin">
	<div class="cpt-pc-col cpt-pc-s2 cpt-pc-no-padding">
		<#= model.get('labels').name #>
	</div>
	<div class="cpt-pc-col cpt-pc-s2 cpt-pc-no-padding">
		<#= model.get('slug') #>
	</div>
	<div class="cpt-pc-col cpt-pc-s6 cpt-pc-no-padding">
		<#= model.get('description') #>
	</div>
	<div class="cpt-pc-col cpt-pc-s2 cpt-pc-no-padding">
		<a href="javascript:void(0)" class="cpt-pc-delete"><i class="cpt-pc-material-icons cpt-pc-red-text cpt-pc-right">delete</i></a>
		<a href="javascript:void(0)" class="cpt-pc-edit"><i class="cpt-pc-material-icons cpt-pc-teal-text cpt-pc-right">edit</i></a>
	</div>
</div>

